"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
from glob import glob

APP = ['OPVsyndeo.py']
DATA_FILES = [
    ('icons',glob('icons/*.png'))
]
OPTIONS = {
    'iconfile': 'icons/red.png',
    'packages': ['sshuttle', 'subprocess', 'urllib', 'rumps', 'packaging', 'setuptools', 'py2app']
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
