"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py
"""

from setuptools import setup, find_packages
from glob import glob

setup(
    name='OPVsyndeo',
    version = '1.0.0',
    packages = find_packages(),
    data_files = [
        ('icons',glob('icons/*.png'))
    ],
    install_requires = [
        'sshuttle',
        'rumps'
    ],
    setup_requires = [
        'setuptools'
    ],
    entry_points = {
        'console_scripts': [
            'opvsyndeo = OPVsyndeo:OPVsyndeoApp.main'
        ]
    }
)
